name: Actualizar Google Sheets

on:
  schedule:
    - cron: '40 3 * * *'  # Nueva hora de ejecuci칩n: 3:40 AM UTC
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PYTHONUNBUFFERED: 1
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      MAX_WORKERS: 6
      REQUEST_TIMEOUT: 20

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar instalaci칩n de gspread (opcional)
        run: pip show gspread || echo "gspread no est치 instalado correctamente"

      - name: Crear archivo de credenciales de Google
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > google-credentials.json

      - name: Ejecutar scraper optimizado
        run: python -u scraper.py
