name: Unificación de Datos y Actualización

on:
  schedule:
    - cron: '40 3 * * *'
  workflow_dispatch:

jobs:
  unification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar unificación de datos
        run: python scraper.py
