name: Generate and Commit GeoJSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install feedparser geopy requests

      - name: Run script to generate new data
        run: |
          python m357_map.py

      - name: Combine existing and new GeoJSON data
        run: |
          if [ -f new_data.geojson ]; then
            if [ -f masoneria_alertas.geojson ]; then
              python combine_geojson.py masoneria_alertas.geojson new_data.geojson masoneria_alertas.geojson
            else
              mv new_data.geojson masoneria_alertas.geojson
            fi
          else
            echo "No new data generated. Skipping combination."
            exit 0

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add .
          if [ -n "$(git diff --cached)" ]; then
            git commit -m "Auto-update from GitHub Actions $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
