name: Actualizar Google Sheets

on:
  schedule:
    - cron: '40 3 * * *'  # Nueva hora de ejecución: 3:40 AM UTC
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PYTHONUNBUFFERED: 1
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      MAX_WORKERS: 6
      REQUEST_TIMEOUT: 20

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Crear entorno virtual
        run: python -m venv venv

      - name: Activar entorno virtual y limpiar caché
        run: |
          source venv/bin/activate
          pip cache purge
          pip install --no-cache-dir --upgrade pip setuptools wheel

      - name: Instalar dependencias en el entorno virtual
        run: |
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Verificar instalación de gspread
        run: |
          source venv/bin/activate
          pip show gspread

      - name: Instalar modelo spaCy
        run: |
          source venv/bin/activate
          python -m spacy download en_core_web_sm

      - name: Ejecutar scraper optimizado
        run: |
          source venv/bin/activate
          python google_sheets_scraper/scraper.py
