name: Wikipedia Data Update

on:
  schedule:
    - cron: '0 3 1,16 * *'   # Corre todos los días 1 y 16 de cada mes a las 3:00 AM UTC
  workflow_dispatch:   # Permite ejecución manual

jobs:
  update-wikipedia:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 1: Ejecuta tu scraper que genera/actualiza wikipedia_data.json
      - name: Run Wikipedia scraper
        run: |
          python wikipedia_scraper.py

      # Paso 2: Crear wikipedia_data.geojson usando el script combinado
      - name: Generate Wikipedia GeoJSON
        run: |
          python create_wikipedia_geojson.py

      # Paso 3: Commit y push de ambas salidas (json + geojson)
      - name: Commit and push updated data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # Hacer pull antes de intentar el push
          git pull --rebase origin main

          git add wikipedia_data.json wikipedia_data.geojson
          
          # Si no hay cambios reales, el commit puede fallar 
          git commit -m "Auto-update: Wikipedia data $(date +'%Y-%m-%d')" || echo "No changes to commit."
          
          # Hacer push con los cambios actualizados
          git push origin main
