name: Wikipedia Data Update

on:
  schedule:
    - cron: '0 3 * * *'   # Corre todos los días a las 3:00 AM UTC
  workflow_dispatch:       # Permite ejecución manual

jobs:
  update-wikipedia:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Asegúrate de que en requirements.txt figuren geopy y geojson
          # ej: 
          # geojson==2.5.0
          # geopy==2.3.0

      # Paso 1: Ejecuta tu scraper que genera/actualiza wikipedia_data.json
      - name: Run Wikipedia scraper
        run: |
          python wikipedia_scraper.py

      # Paso 2: Crear wikipedia_data.geojson usando el script combinado
      # que aprovecha lat/lon si existen, o geocodifica si hay "location"
      - name: Generate Wikipedia GeoJSON
        run: |
          python create_wikipedia_geojson.py

      # Paso 3: Commit y push de ambas salidas (json + geojson)
      - name: Commit updated data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add wikipedia_data.json wikipedia_data.geojson
          # Si no hay cambios reales, el commit puede fallar 
          # o no hará nada. No pasa nada, el job seguirá.
          git commit -m "Auto-update: Wikipedia data $(date +'%Y-%m-%d')" || echo "No changes to commit."
          git push
