name: Wikipedia Data Update

on:
  schedule:
    - cron: '0 3 * * *'  # Ejecución diaria a las 3:00 AM UTC
  workflow_dispatch:  # Permite la ejecución manual desde GitHub Actions

jobs:
  update-wikipedia:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Wikipedia scraper
        run: |
          python wikipedia_scraper.py

      - name: Commit updated data
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add wikipedia_data.json
          git commit -m "Auto-update: Wikipedia data $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
